django_app:
  build: .
  image: django_app
  container_name: django_cont
  ports:
    - "8000:8000"
  command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
  restart: always
  healthcheck:
    test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 30s
  networks:
    - notes-app-nw
